package com.shengsiyuan.model;
// Generated 2018-7-9 10:42:52 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
)
public class Student  implements java.io.Serializable {


     private long id;
     private String username;
     private String address;
     private int age;

    public Student() {
    }

    public Student(String username, String address, int age) {
       this.username = username;
       this.address = address;
       this.age = age;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")
    
    @Column(name="id", nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    @Column(name="username")
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="age")
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }




}


